%%{init: {'theme': 'base', 'themeVariables': { 'primaryColor': '#E3F2FD', 'lineColor': '#424242'}, 'flowchart': {'curve': 'basis', 'nodeSpacing': 30, 'rankSpacing': 50}}}%%

flowchart LR
    subgraph INPUT["INPUT"]
        direction TB
        I1["ImzML"]
        I2["Bruker"]
        I3["Future"]:::future
    end

    subgraph DETECT["DETECTION"]
        R["Registry"]
    end

    subgraph READ["READING"]
        direction TB
        R1["iter_spectra()"]
        R2["get_mass_axis()"]
        R3["Metadata"]
    end

    subgraph RESAMPLE["RESAMPLING"]
        direction TB
        RS1["Decision Tree"]
        RS2["Mass Axis Gen"]
        RS3["Strategy"]
    end

    subgraph CONVERT["CONVERSION"]
        direction TB
        C1["1. Initialize"]
        C2["2. Create Structures"]
        C3["3. Process Spectra"]
        C4["4. Finalize"]
        C5["5. Save"]
        C1 --> C2 --> C3 --> C4 --> C5
    end

    subgraph OUTPUT["SPATIALDATA"]
        direction TB
        O1["Tables"]
        O2["Shapes"]
        O3["Images"]
        O4["Metadata"]
    end

    subgraph ANALYSIS["ANALYSIS"]
        direction TB
        A1["Scanpy"]
        A2["Squidpy"]
        A3["Napari"]
    end

    INPUT --> DETECT --> READ --> RESAMPLE --> CONVERT --> OUTPUT --> ANALYSIS

    classDef future fill:#FAFAFA,stroke:#9E9E9E,stroke-dasharray: 5 5
